FROM php:7.2-alpine

MAINTAINER Mike Georgeff <mike.georgeff@uscca.com>

RUN addgroup -g 1000 -S delta && \
	adduser -u 1000 -h /home/delta -S -G delta delta && \
	chown -R delta:delta /home/delta

RUN apk add --update wget \
					 git \
					 nano \
					 supervisor && \
					 rm /var/cache/apk/* && \
					 touch /etc/supervisord.conf

COPY php.ini /usr/local/etc/php/php.ini					 
		
WORKDIR /home/delta								  

CMD ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]