FROM mikegeorgeff/php:7.2-cli

MAINTAINER Mike Georgeff <mike.georgeff@uscca.com>

RUN apk add --update nginx php-fpm@php

COPY nginx.conf /etc/nginx/nginx.conf
COPY supervisord.fpm.conf /etc/supervisord.conf
COPY www.conf /etc/php7/php-fpm.d/www.conf

CMD ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]